export type WordItem = {
  id: string;
  deckId: string;
  english: string;
  hebrew: string;
  level: 1 | 2;
  category: string;
};

// v0 seed content (expand later + move to DB)
export const WORDS: WordItem[] = [
  // --- L1: Animals (20) ---
  { id: 'cat', deckId: 'lvl1-animals', english: 'cat', hebrew: 'חתול', level: 1, category: 'animals' },
  { id: 'dog', deckId: 'lvl1-animals', english: 'dog', hebrew: 'כלב', level: 1, category: 'animals' },
  { id: 'mouse', deckId: 'lvl1-animals', english: 'mouse', hebrew: 'עכבר', level: 1, category: 'animals' },
  { id: 'horse', deckId: 'lvl1-animals', english: 'horse', hebrew: 'סוס', level: 1, category: 'animals' },
  { id: 'lion', deckId: 'lvl1-animals', english: 'lion', hebrew: 'אריה', level: 1, category: 'animals' },
  { id: 'bear', deckId: 'lvl1-animals', english: 'bear', hebrew: 'דוב', level: 1, category: 'animals' },
  { id: 'tiger', deckId: 'lvl1-animals', english: 'tiger', hebrew: 'נמר', level: 1, category: 'animals' },
  { id: 'rabbit', deckId: 'lvl1-animals', english: 'rabbit', hebrew: 'ארנב', level: 1, category: 'animals' },
  { id: 'monkey', deckId: 'lvl1-animals', english: 'monkey', hebrew: 'קוף', level: 1, category: 'animals' },
  { id: 'elephant', deckId: 'lvl1-animals', english: 'elephant', hebrew: 'פיל', level: 1, category: 'animals' },
  { id: 'giraffe', deckId: 'lvl1-animals', english: 'giraffe', hebrew: 'ג׳ירפה', level: 1, category: 'animals' },
  { id: 'zebra', deckId: 'lvl1-animals', english: 'zebra', hebrew: 'זברה', level: 1, category: 'animals' },
  { id: 'cow', deckId: 'lvl1-animals', english: 'cow', hebrew: 'פרה', level: 1, category: 'animals' },
  { id: 'pig', deckId: 'lvl1-animals', english: 'pig', hebrew: 'חזיר', level: 1, category: 'animals' },
  { id: 'sheep', deckId: 'lvl1-animals', english: 'sheep', hebrew: 'כבשה', level: 1, category: 'animals' },
  { id: 'goat', deckId: 'lvl1-animals', english: 'goat', hebrew: 'עז', level: 1, category: 'animals' },
  { id: 'chicken', deckId: 'lvl1-animals', english: 'chicken', hebrew: 'תרנגולת', level: 1, category: 'animals' },
  { id: 'duck', deckId: 'lvl1-animals', english: 'duck', hebrew: 'ברווז', level: 1, category: 'animals' },
  { id: 'fish', deckId: 'lvl1-animals', english: 'fish', hebrew: 'דג', level: 1, category: 'animals' },
  { id: 'bird', deckId: 'lvl1-animals', english: 'bird', hebrew: 'ציפור', level: 1, category: 'animals' },

  // --- L1: Colors (20) ---
  { id: 'red', deckId: 'lvl1-colors', english: 'red', hebrew: 'אדום', level: 1, category: 'colors' },
  { id: 'blue', deckId: 'lvl1-colors', english: 'blue', hebrew: 'כחול', level: 1, category: 'colors' },
  { id: 'green', deckId: 'lvl1-colors', english: 'green', hebrew: 'ירוק', level: 1, category: 'colors' },
  { id: 'yellow', deckId: 'lvl1-colors', english: 'yellow', hebrew: 'צהוב', level: 1, category: 'colors' },
  { id: 'black', deckId: 'lvl1-colors', english: 'black', hebrew: 'שחור', level: 1, category: 'colors' },
  { id: 'white', deckId: 'lvl1-colors', english: 'white', hebrew: 'לבן', level: 1, category: 'colors' },
  { id: 'pink', deckId: 'lvl1-colors', english: 'pink', hebrew: 'ורוד', level: 1, category: 'colors' },
  { id: 'purple', deckId: 'lvl1-colors', english: 'purple', hebrew: 'סגול', level: 1, category: 'colors' },
  { id: 'orange', deckId: 'lvl1-colors', english: 'orange', hebrew: 'כתום', level: 1, category: 'colors' },
  { id: 'brown', deckId: 'lvl1-colors', english: 'brown', hebrew: 'חום', level: 1, category: 'colors' },
  { id: 'gray', deckId: 'lvl1-colors', english: 'gray', hebrew: 'אפור', level: 1, category: 'colors' },
  { id: 'gold', deckId: 'lvl1-colors', english: 'gold', hebrew: 'זהב', level: 1, category: 'colors' },
  { id: 'silver', deckId: 'lvl1-colors', english: 'silver', hebrew: 'כסף', level: 1, category: 'colors' },
  { id: 'light', deckId: 'lvl1-colors', english: 'light', hebrew: 'בהיר', level: 1, category: 'colors' },
  { id: 'dark', deckId: 'lvl1-colors', english: 'dark', hebrew: 'כהה', level: 1, category: 'colors' },
  { id: 'color', deckId: 'lvl1-colors', english: 'color', hebrew: 'צבע', level: 1, category: 'colors' },
  { id: 'rainbow', deckId: 'lvl1-colors', english: 'rainbow', hebrew: 'קשת', level: 1, category: 'colors' },
  { id: 'bright', deckId: 'lvl1-colors', english: 'bright', hebrew: 'בוהק', level: 1, category: 'colors' },
  { id: 'paint', deckId: 'lvl1-colors', english: 'paint', hebrew: 'צבע (לצבוע)', level: 1, category: 'colors' },
  { id: 'crayon', deckId: 'lvl1-colors', english: 'crayon', hebrew: 'טוש/צבע שעווה', level: 1, category: 'colors' },

  // --- L1: School (20) ---
  { id: 'book', deckId: 'lvl1-school', english: 'book', hebrew: 'ספר', level: 1, category: 'school' },
  { id: 'pencil', deckId: 'lvl1-school', english: 'pencil', hebrew: 'עיפרון', level: 1, category: 'school' },
  { id: 'pen', deckId: 'lvl1-school', english: 'pen', hebrew: 'עט', level: 1, category: 'school' },
  { id: 'bag', deckId: 'lvl1-school', english: 'bag', hebrew: 'תיק', level: 1, category: 'school' },
  { id: 'teacher', deckId: 'lvl1-school', english: 'teacher', hebrew: 'מורה', level: 1, category: 'school' },
  { id: 'student', deckId: 'lvl1-school', english: 'student', hebrew: 'תלמיד', level: 1, category: 'school' },
  { id: 'class', deckId: 'lvl1-school', english: 'class', hebrew: 'כיתה', level: 1, category: 'school' },
  { id: 'school', deckId: 'lvl1-school', english: 'school', hebrew: 'בית ספר', level: 1, category: 'school' },
  { id: 'desk', deckId: 'lvl1-school', english: 'desk', hebrew: 'שולחן', level: 1, category: 'school' },
  { id: 'chair', deckId: 'lvl1-school', english: 'chair', hebrew: 'כיסא', level: 1, category: 'school' },
  { id: 'board', deckId: 'lvl1-school', english: 'board', hebrew: 'לוח', level: 1, category: 'school' },
  { id: 'eraser', deckId: 'lvl1-school', english: 'eraser', hebrew: 'מחק', level: 1, category: 'school' },
  { id: 'ruler', deckId: 'lvl1-school', english: 'ruler', hebrew: 'סרגל', level: 1, category: 'school' },
  { id: 'notebook', deckId: 'lvl1-school', english: 'notebook', hebrew: 'מחברת', level: 1, category: 'school' },
  { id: 'paper', deckId: 'lvl1-school', english: 'paper', hebrew: 'דף', level: 1, category: 'school' },
  { id: 'test', deckId: 'lvl1-school', english: 'test', hebrew: 'מבחן', level: 1, category: 'school' },
  { id: 'homework', deckId: 'lvl1-school', english: 'homework', hebrew: 'שיעורי בית', level: 1, category: 'school' },
  { id: 'break', deckId: 'lvl1-school', english: 'break', hebrew: 'הפסקה', level: 1, category: 'school' },
  { id: 'lunch', deckId: 'lvl1-school', english: 'lunch', hebrew: 'ארוחת צהריים', level: 1, category: 'school' },
  { id: 'marker', deckId: 'lvl1-school', english: 'marker', hebrew: 'טוש', level: 1, category: 'school' },

  // --- L1: Food (20) ---
  { id: 'apple', deckId: 'lvl1-food', english: 'apple', hebrew: 'תפוח', level: 1, category: 'food' },
  { id: 'banana', deckId: 'lvl1-food', english: 'banana', hebrew: 'בננה', level: 1, category: 'food' },
  { id: 'bread', deckId: 'lvl1-food', english: 'bread', hebrew: 'לחם', level: 1, category: 'food' },
  { id: 'cheese', deckId: 'lvl1-food', english: 'cheese', hebrew: 'גבינה', level: 1, category: 'food' },
  { id: 'milk', deckId: 'lvl1-food', english: 'milk', hebrew: 'חלב', level: 1, category: 'food' },
  { id: 'water', deckId: 'lvl1-food', english: 'water', hebrew: 'מים', level: 1, category: 'food' },
  { id: 'juice', deckId: 'lvl1-food', english: 'juice', hebrew: 'מיץ', level: 1, category: 'food' },
  { id: 'egg', deckId: 'lvl1-food', english: 'egg', hebrew: 'ביצה', level: 1, category: 'food' },
  { id: 'fish_food', deckId: 'lvl1-food', english: 'fish', hebrew: 'דג', level: 1, category: 'food' },
  { id: 'chicken_food', deckId: 'lvl1-food', english: 'chicken', hebrew: 'עוף', level: 1, category: 'food' },
  { id: 'rice', deckId: 'lvl1-food', english: 'rice', hebrew: 'אורז', level: 1, category: 'food' },
  { id: 'pasta', deckId: 'lvl1-food', english: 'pasta', hebrew: 'פסטה', level: 1, category: 'food' },
  { id: 'pizza', deckId: 'lvl1-food', english: 'pizza', hebrew: 'פיצה', level: 1, category: 'food' },
  { id: 'salad', deckId: 'lvl1-food', english: 'salad', hebrew: 'סלט', level: 1, category: 'food' },
  { id: 'soup', deckId: 'lvl1-food', english: 'soup', hebrew: 'מרק', level: 1, category: 'food' },
  { id: 'cookie', deckId: 'lvl1-food', english: 'cookie', hebrew: 'עוגייה', level: 1, category: 'food' },
  { id: 'cake', deckId: 'lvl1-food', english: 'cake', hebrew: 'עוגה', level: 1, category: 'food' },
  { id: 'ice_cream', deckId: 'lvl1-food', english: 'ice cream', hebrew: 'גלידה', level: 1, category: 'food' },
  { id: 'chocolate', deckId: 'lvl1-food', english: 'chocolate', hebrew: 'שוקולד', level: 1, category: 'food' },
  { id: 'sandwich', deckId: 'lvl1-food', english: 'sandwich', hebrew: 'סנדוויץ׳', level: 1, category: 'food' },

  // --- L1: Family (20) ---
  { id: 'mom', deckId: 'lvl1-family', english: 'mom', hebrew: 'אמא', level: 1, category: 'family' },
  { id: 'dad', deckId: 'lvl1-family', english: 'dad', hebrew: 'אבא', level: 1, category: 'family' },
  { id: 'sister', deckId: 'lvl1-family', english: 'sister', hebrew: 'אחות', level: 1, category: 'family' },
  { id: 'brother', deckId: 'lvl1-family', english: 'brother', hebrew: 'אח', level: 1, category: 'family' },
  { id: 'grandma', deckId: 'lvl1-family', english: 'grandma', hebrew: 'סבתא', level: 1, category: 'family' },
  { id: 'grandpa', deckId: 'lvl1-family', english: 'grandpa', hebrew: 'סבא', level: 1, category: 'family' },
  { id: 'baby', deckId: 'lvl1-family', english: 'baby', hebrew: 'תינוק', level: 1, category: 'family' },
  { id: 'family', deckId: 'lvl1-family', english: 'family', hebrew: 'משפחה', level: 1, category: 'family' },
  { id: 'aunt', deckId: 'lvl1-family', english: 'aunt', hebrew: 'דודה', level: 1, category: 'family' },
  { id: 'uncle', deckId: 'lvl1-family', english: 'uncle', hebrew: 'דוד', level: 1, category: 'family' },
  { id: 'cousin', deckId: 'lvl1-family', english: 'cousin', hebrew: 'בן/בת דוד', level: 1, category: 'family' },
  { id: 'parent', deckId: 'lvl1-family', english: 'parent', hebrew: 'הורה', level: 1, category: 'family' },
  { id: 'son', deckId: 'lvl1-family', english: 'son', hebrew: 'בן', level: 1, category: 'family' },
  { id: 'daughter', deckId: 'lvl1-family', english: 'daughter', hebrew: 'בת', level: 1, category: 'family' },
  { id: 'kid', deckId: 'lvl1-family', english: 'kid', hebrew: 'ילד', level: 1, category: 'family' },
  { id: 'boy', deckId: 'lvl1-family', english: 'boy', hebrew: 'ילד (בן)', level: 1, category: 'family' },
  { id: 'girl', deckId: 'lvl1-family', english: 'girl', hebrew: 'ילדה', level: 1, category: 'family' },
  { id: 'name', deckId: 'lvl1-family', english: 'name', hebrew: 'שם', level: 1, category: 'family' },
  { id: 'home_family', deckId: 'lvl1-family', english: 'home', hebrew: 'בית', level: 1, category: 'family' },
  { id: 'love', deckId: 'lvl1-family', english: 'love', hebrew: 'אהבה', level: 1, category: 'family' },

  // --- L1: Toys (20) ---
  { id: 'toy', deckId: 'lvl1-toys', english: 'toy', hebrew: 'צעצוע', level: 1, category: 'toys' },
  { id: 'ball', deckId: 'lvl1-toys', english: 'ball', hebrew: 'כדור', level: 1, category: 'toys' },
  { id: 'doll', deckId: 'lvl1-toys', english: 'doll', hebrew: 'בובה', level: 1, category: 'toys' },
  { id: 'car_toy', deckId: 'lvl1-toys', english: 'car', hebrew: 'מכונית', level: 1, category: 'toys' },
  { id: 'train', deckId: 'lvl1-toys', english: 'train', hebrew: 'רכבת', level: 1, category: 'toys' },
  { id: 'blocks', deckId: 'lvl1-toys', english: 'blocks', hebrew: 'קוביות', level: 1, category: 'toys' },
  { id: 'lego', deckId: 'lvl1-toys', english: 'lego', hebrew: 'לגו', level: 1, category: 'toys' },
  { id: 'puzzle', deckId: 'lvl1-toys', english: 'puzzle', hebrew: 'פאזל', level: 1, category: 'toys' },
  { id: 'teddy', deckId: 'lvl1-toys', english: 'teddy bear', hebrew: 'דובי', level: 1, category: 'toys' },
  { id: 'game', deckId: 'lvl1-toys', english: 'game', hebrew: 'משחק', level: 1, category: 'toys' },
  { id: 'rope', deckId: 'lvl1-toys', english: 'rope', hebrew: 'חבל', level: 1, category: 'toys' },
  { id: 'kite', deckId: 'lvl1-toys', english: 'kite', hebrew: 'עפיפון', level: 1, category: 'toys' },
  { id: 'robot', deckId: 'lvl1-toys', english: 'robot', hebrew: 'רובוט', level: 1, category: 'toys' },
  { id: 'yo_yo', deckId: 'lvl1-toys', english: 'yo-yo', hebrew: 'יו-יו', level: 1, category: 'toys' },
  { id: 'bike', deckId: 'lvl1-toys', english: 'bike', hebrew: 'אופניים', level: 1, category: 'toys' },
  { id: 'scooter', deckId: 'lvl1-toys', english: 'scooter', hebrew: 'קורקינט', level: 1, category: 'toys' },
  { id: 'skateboard', deckId: 'lvl1-toys', english: 'skateboard', hebrew: 'סקייטבורד', level: 1, category: 'toys' },
  { id: 'book_toy', deckId: 'lvl1-toys', english: 'book', hebrew: 'ספר', level: 1, category: 'toys' },
  { id: 'tablet', deckId: 'lvl1-toys', english: 'tablet', hebrew: 'טאבלט', level: 1, category: 'toys' },
  { id: 'controller', deckId: 'lvl1-toys', english: 'controller', hebrew: 'שלט משחק', level: 1, category: 'toys' },

  // --- L1: Clothes (20) ---
  { id: 'shirt', deckId: 'lvl1-clothes', english: 'shirt', hebrew: 'חולצה', level: 1, category: 'clothes' },
  { id: 'pants', deckId: 'lvl1-clothes', english: 'pants', hebrew: 'מכנסיים', level: 1, category: 'clothes' },
  { id: 'dress', deckId: 'lvl1-clothes', english: 'dress', hebrew: 'שמלה', level: 1, category: 'clothes' },
  { id: 'skirt', deckId: 'lvl1-clothes', english: 'skirt', hebrew: 'חצאית', level: 1, category: 'clothes' },
  { id: 'shoes', deckId: 'lvl1-clothes', english: 'shoes', hebrew: 'נעליים', level: 1, category: 'clothes' },
  { id: 'socks', deckId: 'lvl1-clothes', english: 'socks', hebrew: 'גרביים', level: 1, category: 'clothes' },
  { id: 'hat', deckId: 'lvl1-clothes', english: 'hat', hebrew: 'כובע', level: 1, category: 'clothes' },
  { id: 'coat', deckId: 'lvl1-clothes', english: 'coat', hebrew: 'מעיל', level: 1, category: 'clothes' },
  { id: 'jacket', deckId: 'lvl1-clothes', english: 'jacket', hebrew: 'ג׳קט', level: 1, category: 'clothes' },
  { id: 'sweater', deckId: 'lvl1-clothes', english: 'sweater', hebrew: 'סוודר', level: 1, category: 'clothes' },
  { id: 'shorts', deckId: 'lvl1-clothes', english: 'shorts', hebrew: 'מכנס קצר', level: 1, category: 'clothes' },
  { id: 'scarf', deckId: 'lvl1-clothes', english: 'scarf', hebrew: 'צעיף', level: 1, category: 'clothes' },
  { id: 'gloves', deckId: 'lvl1-clothes', english: 'gloves', hebrew: 'כפפות', level: 1, category: 'clothes' },
  { id: 'boots', deckId: 'lvl1-clothes', english: 'boots', hebrew: 'מגפיים', level: 1, category: 'clothes' },
  { id: 'belt', deckId: 'lvl1-clothes', english: 'belt', hebrew: 'חגורה', level: 1, category: 'clothes' },
  { id: 'pajamas', deckId: 'lvl1-clothes', english: 'pajamas', hebrew: 'פיג׳מה', level: 1, category: 'clothes' },
  { id: 'uniform', deckId: 'lvl1-clothes', english: 'uniform', hebrew: 'מדים', level: 1, category: 'clothes' },
  { id: 'tshirt', deckId: 'lvl1-clothes', english: 'T-shirt', hebrew: 'טי-שירט', level: 1, category: 'clothes' },
  { id: 'sandals', deckId: 'lvl1-clothes', english: 'sandals', hebrew: 'סנדלים', level: 1, category: 'clothes' },
  { id: 'cap', deckId: 'lvl1-clothes', english: 'cap', hebrew: 'כובע מצחייה', level: 1, category: 'clothes' },

  // --- L1: Numbers 1-20 (20) ---
  { id: 'one', deckId: 'lvl1-numbers', english: 'one', hebrew: 'אחד', level: 1, category: 'numbers' },
  { id: 'two', deckId: 'lvl1-numbers', english: 'two', hebrew: 'שניים', level: 1, category: 'numbers' },
  { id: 'three', deckId: 'lvl1-numbers', english: 'three', hebrew: 'שלוש', level: 1, category: 'numbers' },
  { id: 'four', deckId: 'lvl1-numbers', english: 'four', hebrew: 'ארבע', level: 1, category: 'numbers' },
  { id: 'five', deckId: 'lvl1-numbers', english: 'five', hebrew: 'חמש', level: 1, category: 'numbers' },
  { id: 'six', deckId: 'lvl1-numbers', english: 'six', hebrew: 'שש', level: 1, category: 'numbers' },
  { id: 'seven', deckId: 'lvl1-numbers', english: 'seven', hebrew: 'שבע', level: 1, category: 'numbers' },
  { id: 'eight', deckId: 'lvl1-numbers', english: 'eight', hebrew: 'שמונה', level: 1, category: 'numbers' },
  { id: 'nine', deckId: 'lvl1-numbers', english: 'nine', hebrew: 'תשע', level: 1, category: 'numbers' },
  { id: 'ten', deckId: 'lvl1-numbers', english: 'ten', hebrew: 'עשר', level: 1, category: 'numbers' },
  { id: 'eleven', deckId: 'lvl1-numbers', english: 'eleven', hebrew: 'אחד עשר', level: 1, category: 'numbers' },
  { id: 'twelve', deckId: 'lvl1-numbers', english: 'twelve', hebrew: 'שניים עשר', level: 1, category: 'numbers' },
  { id: 'thirteen', deckId: 'lvl1-numbers', english: 'thirteen', hebrew: 'שלושה עשר', level: 1, category: 'numbers' },
  { id: 'fourteen', deckId: 'lvl1-numbers', english: 'fourteen', hebrew: 'ארבעה עשר', level: 1, category: 'numbers' },
  { id: 'fifteen', deckId: 'lvl1-numbers', english: 'fifteen', hebrew: 'חמישה עשר', level: 1, category: 'numbers' },
  { id: 'sixteen', deckId: 'lvl1-numbers', english: 'sixteen', hebrew: 'שישה עשר', level: 1, category: 'numbers' },
  { id: 'seventeen', deckId: 'lvl1-numbers', english: 'seventeen', hebrew: 'שבעה עשר', level: 1, category: 'numbers' },
  { id: 'eighteen', deckId: 'lvl1-numbers', english: 'eighteen', hebrew: 'שמונה עשר', level: 1, category: 'numbers' },
  { id: 'nineteen', deckId: 'lvl1-numbers', english: 'nineteen', hebrew: 'תשעה עשר', level: 1, category: 'numbers' },
  { id: 'twenty', deckId: 'lvl1-numbers', english: 'twenty', hebrew: 'עשרים', level: 1, category: 'numbers' },

  // --- L1: Body (20) ---
  { id: 'head', deckId: 'lvl1-body', english: 'head', hebrew: 'ראש', level: 1, category: 'body' },
  { id: 'hair', deckId: 'lvl1-body', english: 'hair', hebrew: 'שיער', level: 1, category: 'body' },
  { id: 'eye', deckId: 'lvl1-body', english: 'eye', hebrew: 'עין', level: 1, category: 'body' },
  { id: 'ear', deckId: 'lvl1-body', english: 'ear', hebrew: 'אוזן', level: 1, category: 'body' },
  { id: 'nose', deckId: 'lvl1-body', english: 'nose', hebrew: 'אף', level: 1, category: 'body' },
  { id: 'mouth', deckId: 'lvl1-body', english: 'mouth', hebrew: 'פה', level: 1, category: 'body' },
  { id: 'tooth', deckId: 'lvl1-body', english: 'tooth', hebrew: 'שן', level: 1, category: 'body' },
  { id: 'hand', deckId: 'lvl1-body', english: 'hand', hebrew: 'יד', level: 1, category: 'body' },
  { id: 'finger', deckId: 'lvl1-body', english: 'finger', hebrew: 'אצבע', level: 1, category: 'body' },
  { id: 'arm', deckId: 'lvl1-body', english: 'arm', hebrew: 'זרוע', level: 1, category: 'body' },
  { id: 'leg', deckId: 'lvl1-body', english: 'leg', hebrew: 'רגל', level: 1, category: 'body' },
  { id: 'foot', deckId: 'lvl1-body', english: 'foot', hebrew: 'כף רגל', level: 1, category: 'body' },
  { id: 'knee', deckId: 'lvl1-body', english: 'knee', hebrew: 'ברך', level: 1, category: 'body' },
  { id: 'shoulder', deckId: 'lvl1-body', english: 'shoulder', hebrew: 'כתף', level: 1, category: 'body' },
  { id: 'stomach', deckId: 'lvl1-body', english: 'stomach', hebrew: 'בטן', level: 1, category: 'body' },
  { id: 'back', deckId: 'lvl1-body', english: 'back', hebrew: 'גב', level: 1, category: 'body' },
  { id: 'face', deckId: 'lvl1-body', english: 'face', hebrew: 'פנים', level: 1, category: 'body' },
  { id: 'neck', deckId: 'lvl1-body', english: 'neck', hebrew: 'צוואר', level: 1, category: 'body' },
  { id: 'heart', deckId: 'lvl1-body', english: 'heart', hebrew: 'לב', level: 1, category: 'body' },
  { id: 'skin', deckId: 'lvl1-body', english: 'skin', hebrew: 'עור', level: 1, category: 'body' },

  // --- L1: Home (20) ---
  { id: 'home', deckId: 'lvl1-home', english: 'home', hebrew: 'בית', level: 1, category: 'home' },
  { id: 'room', deckId: 'lvl1-home', english: 'room', hebrew: 'חדר', level: 1, category: 'home' },
  { id: 'bed', deckId: 'lvl1-home', english: 'bed', hebrew: 'מיטה', level: 1, category: 'home' },
  { id: 'door', deckId: 'lvl1-home', english: 'door', hebrew: 'דלת', level: 1, category: 'home' },
  { id: 'window', deckId: 'lvl1-home', english: 'window', hebrew: 'חלון', level: 1, category: 'home' },
  { id: 'table', deckId: 'lvl1-home', english: 'table', hebrew: 'שולחן', level: 1, category: 'home' },
  { id: 'chair_home', deckId: 'lvl1-home', english: 'chair', hebrew: 'כיסא', level: 1, category: 'home' },
  { id: 'sofa', deckId: 'lvl1-home', english: 'sofa', hebrew: 'ספה', level: 1, category: 'home' },
  { id: 'kitchen', deckId: 'lvl1-home', english: 'kitchen', hebrew: 'מטבח', level: 1, category: 'home' },
  { id: 'bathroom', deckId: 'lvl1-home', english: 'bathroom', hebrew: 'שירותים/אמבטיה', level: 1, category: 'home' },
  { id: 'lamp', deckId: 'lvl1-home', english: 'lamp', hebrew: 'מנורה', level: 1, category: 'home' },
  { id: 'light_home', deckId: 'lvl1-home', english: 'light', hebrew: 'אור', level: 1, category: 'home' },
  { id: 'tv', deckId: 'lvl1-home', english: 'TV', hebrew: 'טלוויזיה', level: 1, category: 'home' },
  { id: 'computer', deckId: 'lvl1-home', english: 'computer', hebrew: 'מחשב', level: 1, category: 'home' },
  { id: 'phone', deckId: 'lvl1-home', english: 'phone', hebrew: 'טלפון', level: 1, category: 'home' },
  { id: 'fridge', deckId: 'lvl1-home', english: 'fridge', hebrew: 'מקרר', level: 1, category: 'home' },
  { id: 'oven', deckId: 'lvl1-home', english: 'oven', hebrew: 'תנור', level: 1, category: 'home' },
  { id: 'plate', deckId: 'lvl1-home', english: 'plate', hebrew: 'צלחת', level: 1, category: 'home' },
  { id: 'cup', deckId: 'lvl1-home', english: 'cup', hebrew: 'כוס', level: 1, category: 'home' },
  { id: 'spoon', deckId: 'lvl1-home', english: 'spoon', hebrew: 'כף', level: 1, category: 'home' },

  // --- L2 (small starter, still kept) ---
  { id: 'run', deckId: 'lvl2-verbs', english: 'run', hebrew: 'לרוץ', level: 2, category: 'verbs' },
  { id: 'eat', deckId: 'lvl2-verbs', english: 'eat', hebrew: 'לאכול', level: 2, category: 'verbs' },
  { id: 'play', deckId: 'lvl2-verbs', english: 'play', hebrew: 'לשחק', level: 2, category: 'verbs' },
  { id: 'sleep', deckId: 'lvl2-verbs', english: 'sleep', hebrew: 'לישון', level: 2, category: 'verbs' },

  { id: 'big', deckId: 'lvl2-adjectives', english: 'big', hebrew: 'גדול', level: 2, category: 'adjectives' },
  { id: 'small', deckId: 'lvl2-adjectives', english: 'small', hebrew: 'קטן', level: 2, category: 'adjectives' },
  { id: 'happy', deckId: 'lvl2-adjectives', english: 'happy', hebrew: 'שמח', level: 2, category: 'adjectives' },
  { id: 'sad', deckId: 'lvl2-adjectives', english: 'sad', hebrew: 'עצוב', level: 2, category: 'adjectives' },
];
